import { ActionTypes } from "./Reducers"

const ACTIONS = {
    LANGUAGE: 'LANGUAGE',
    NOTIFY: 'NOTIFY',
    USER: 'USER',
    LOGOUT_USER: 'LOGOUT USER',
    CHANGE_THEME: 'CHANGE THEME',
    SET_SHOPPING_CART: 'SET SHOPPING CART',
    SET_USER_DETAILS: 'SET USER DETAILS',
    SET_WISHLIST: 'SET WISHLIST'
}

export default ACTIONS